name: .NET

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 6.0.2xx
      - name: Install dependencies
        run: dotnet restore NugetCliSearch.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore  NugetCliSearch.sln
      - name: Package
        run: dotnet pack --no-build --configuration Release --no-restore NugetCliSearch.sln
      - name: .NET project version updater
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "NugetCliSearch/NugetCliSearch.csproj"
          version: bump-build
      - name: Publish to nuget.org
        if:
          github.ref == 'refs/heads/main'
        run: dotnet nuget push NugetCliSearch/bin/Release/*.nupkg --source "github" --skip-duplicate
